# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

platform :ios,'8.0'
target 'TrendBetting' do

pod 'Toast', '~> 3.0'
pod 'JSONKit-NoWarning', '~> 1.2'
pod 'MJExtension', '~> 3.0.10'
pod 'Toast', '~> 3.0'
pod 'IQKeyboardManager', '~> 4.0.1'
pod 'SVProgressHUD', '~> 2.0.3'
end

